Stripped lqr library

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -697,6 +697,9 @@ PKG_CONFIG
 GIMP_CFLAGS
 GIMP_LIBS
 GIMP_LIBDIR
+LQR_CFLAGS
+LQR_LIBS
+LQR_LIBDIR
 GETTEXT_PACKAGE
 INTLTOOL_DESKTOP_RULE
 INTLTOOL_DIRECTORY_RULE
@@ -762,7 +765,9 @@ CPPFLAGS
 CPP
 PKG_CONFIG
 GIMP_CFLAGS
-GIMP_LIBS'
+GIMP_LIBS
+LQR_CFLAGS
+LQR_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1359,6 +1364,8 @@ Some influential environment variables:
   PKG_CONFIG  path to pkg-config utility
   GIMP_CFLAGS C compiler flags for GIMP, overriding pkg-config
   GIMP_LIBS   linker flags for GIMP, overriding pkg-config
+  LQR_CFLAGS  C compiler flags for LQR, overriding pkg-config
+  LQR_LIBS    linker flags for LQR, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -5872,6 +5879,130 @@ fi
 GIMP_LIBDIR=`$PKG_CONFIG --variable=gimplibdir gimp-2.0`
 
 
+LQR_REQUIRED_VERSION=0.0.1
+
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for LQR" >&5
+echo $ECHO_N "checking for LQR... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LQR_CFLAGS"; then
+        pkg_cv_LQR_CFLAGS="$LQR_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"lqr-1 >= \$LQR_REQUIRED_VERSION\"") >&5
+  ($PKG_CONFIG --exists --print-errors "lqr-1 >= $LQR_REQUIRED_VERSION") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LQR_CFLAGS=`$PKG_CONFIG --cflags "lqr-1 >= $LQR_REQUIRED_VERSION" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LQR_LIBS"; then
+        pkg_cv_LQR_LIBS="$LQR_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"lqr-1 >= \$LQR_REQUIRED_VERSION\"") >&5
+  ($PKG_CONFIG --exists --print-errors "lqr-1 >= $LQR_REQUIRED_VERSION") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LQR_LIBS=`$PKG_CONFIG --libs "lqr-1 >= $LQR_REQUIRED_VERSION" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LQR_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "lqr-1 >= $LQR_REQUIRED_VERSION"`
+        else
+	        LQR_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "lqr-1 >= $LQR_REQUIRED_VERSION"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LQR_PKG_ERRORS" >&5
+
+	{ { echo "$as_me:$LINENO: error: Package requirements (lqr-1 >= $LQR_REQUIRED_VERSION) were not met:
+
+$LQR_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LQR_CFLAGS
+and LQR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (lqr-1 >= $LQR_REQUIRED_VERSION) were not met:
+
+$LQR_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LQR_CFLAGS
+and LQR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LQR_CFLAGS
+and LQR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LQR_CFLAGS
+and LQR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	LQR_CFLAGS=$pkg_cv_LQR_CFLAGS
+	LQR_LIBS=$pkg_cv_LQR_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	:
+fi
+
+LQR_CFLAGS=`$PKG_CONFIG --cflags lqr-1`
+
+
+LQR_LIBS=`$PKG_CONFIG --libs lqr-1`
+
+
+LQR_LIBDIR=`#PACKAGE_CONFIG --variable=libdir lqr-1`
+
+
+
 
 
 GETTEXT_PACKAGE=gimp20-lqr-plugin
@@ -8747,6 +8878,9 @@ PKG_CONFIG!$PKG_CONFIG$ac_delim
 GIMP_CFLAGS!$GIMP_CFLAGS$ac_delim
 GIMP_LIBS!$GIMP_LIBS$ac_delim
 GIMP_LIBDIR!$GIMP_LIBDIR$ac_delim
+LQR_CFLAGS!$LQR_CFLAGS$ac_delim
+LQR_LIBS!$LQR_LIBS$ac_delim
+LQR_LIBDIR!$LQR_LIBDIR$ac_delim
 GETTEXT_PACKAGE!$GETTEXT_PACKAGE$ac_delim
 INTLTOOL_DESKTOP_RULE!$INTLTOOL_DESKTOP_RULE$ac_delim
 INTLTOOL_DIRECTORY_RULE!$INTLTOOL_DIRECTORY_RULE$ac_delim
@@ -8757,9 +8891,6 @@ INTLTOOL_PONG_RULE!$INTLTOOL_PONG_RULE$ac_delim
 INTLTOOL_SERVER_RULE!$INTLTOOL_SERVER_RULE$ac_delim
 INTLTOOL_SHEET_RULE!$INTLTOOL_SHEET_RULE$ac_delim
 INTLTOOL_SOUNDLIST_RULE!$INTLTOOL_SOUNDLIST_RULE$ac_delim
-INTLTOOL_UI_RULE!$INTLTOOL_UI_RULE$ac_delim
-INTLTOOL_XAM_RULE!$INTLTOOL_XAM_RULE$ac_delim
-INTLTOOL_KBD_RULE!$INTLTOOL_KBD_RULE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -8801,6 +8932,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+INTLTOOL_UI_RULE!$INTLTOOL_UI_RULE$ac_delim
+INTLTOOL_XAM_RULE!$INTLTOOL_XAM_RULE$ac_delim
+INTLTOOL_KBD_RULE!$INTLTOOL_KBD_RULE$ac_delim
 INTLTOOL_XML_RULE!$INTLTOOL_XML_RULE$ac_delim
 INTLTOOL_XML_NOMERGE_RULE!$INTLTOOL_XML_NOMERGE_RULE$ac_delim
 INTLTOOL_CAVES_RULE!$INTLTOOL_CAVES_RULE$ac_delim
@@ -8843,7 +8977,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 43; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
